[viewer]
    Title = "GO_Blog"
    Description = "Go语言博客"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com"
    Zhihu = "https://www.zhihu.com"
    Avatar = "/resource/images/avatar.png"
    UserName = "Wvee"
    UserDesc = "Noob"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "1"
    QiniuSecretKey = "2"
    Valine = true
    ValineAppid = "3"
    ValineAppkey = "4"
    ValineServerURL = "5"